### ISSUE TITLE
老哥，怎么构建的时候提示找不到codeck@workspace:^0.0.1

### ISSUE THREAD

**Issue by tap6** [moonrailgun/codeck#2]
![QQ截图20230804022533](https://github.com/moonrailgun/codeck/assets/23492851/bfa83631-ce32-44f9-8862-de1947e8a357)
= =应该和我环境没关系吧老哥，node.js版本v18.17.0，pnpm版本8.6.11，啊这..其他人都能构建吗？

**Comment by moonrailgun** [comment]
fixed, please pull the latest code
